# Generated by Django 4.1.2 on 2022-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='perfil_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
