# Generated by Django 4.1.2 on 2022-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuarios_perfil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='prueba@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
