# Generated by Django 4.1.2 on 2022-11-13 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categorias_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 14, 46, 52, 503324), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 14, 46, 52, 503324), verbose_name='date published'),
        ),
    ]
