# Generated by Django 4.1.2 on 2022-10-23 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='productos',
            name='img2',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='img3',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
