# Generated by Django 4.1.2 on 2022-10-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('send_address', models.CharField(max_length=100)),
                ('send_email', models.EmailField(max_length=100)),
                ('full_name_card', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('exp_date', models.DateField()),
                ('cod', models.CharField(max_length=3)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
    ]
