# Generated by Django 4.1.2 on 2022-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='compras',
            name='departamento',
            field=models.CharField(default='Arequipa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='distrito',
            field=models.CharField(default='Arequipa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='provincia',
            field=models.CharField(default='Arequipa', max_length=50),
            preserve_default=False,
        ),
    ]
