# Generated by Django 4.1.2 on 2022-10-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
