# Generated by Django 4.1.2 on 2022-10-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categoria_productos_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
