# Generated by Django 4.1.2 on 2022-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_compras_prod_id_compras_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='descripcion_compra',
            field=models.TextField(default='Este es un ejemplo de descripcion'),
            preserve_default=False,
        ),
    ]
