# Generated by Django 4.1.2 on 2022-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_categorias_pub_date_alter_productos_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
