# Generated by Django 4.1.2 on 2022-11-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_categorias_pub_date_alter_productos_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('descripcion_compra', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('send_email', models.EmailField(max_length=100)),
                ('send_address', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('full_name_card', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('exp_date', models.DateField()),
                ('cod', models.CharField(max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
