# Generated by Django 4.1.2 on 2022-10-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_proyectos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date Published'),
        ),
    ]
