# Generated by Django 4.1.2 on 2022-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50, null=True)),
                ('imagen', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha del Evento')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Date Published')),
            ],
        ),
    ]
