# Generated by Django 4.1.2 on 2022-11-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productos_pub_date_proyectos_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha del Evento'),
        ),
    ]
