# Generated by Django 4.1.2 on 2022-11-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_proyectos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='lugar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
