# Generated by Django 4.1.2 on 2022-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tcontrol_vidrio_tcontrol_plastico_tcontrol_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
