# Generated by Django 4.1.2 on 2022-11-26 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productos_categoria_delete_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcontrol_papel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
