# Generated by Django 4.1.2 on 2022-11-26 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_tcontrol_papel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcontrol_papel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
