# Generated by Django 4.1.2 on 2022-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tcontrol_papel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
