# Generated by Django 4.1.2 on 2022-12-14 03:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_t_all_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil_image',
            field=models.ImageField(null=True, upload_to=api.models.upload_path),
        ),
    ]
